
kind: Namespace
apiVersion: v1
metadata:
  name: scodex
  labels:
    name: scodex
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scodex-deployment
  namespace: scodex
  labels:
    app: scodex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scodex
  template:
    metadata:
      labels:
        app: scodex
    spec:
      nodeSelector:
        purpose: general
      containers:
      - name: scodex
        image: andresirias/react_page:latest
        ports:
        - containerPort: 3000
      
---
apiVersion: v1
kind: Service
metadata:
  name: scodex-service
  namespace: scodex
spec:
  selector:
    app: scodex
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: scodex
  namespace: scodex
spec:
  hosts:
  - "*"
  gateways:
  - istio-custom/devops-gateway
  http:
    - name: "scodex-routes"
      match:
      - uri: 
          prefix: "/scodex"
      route:
        - destination:
            host: scodex-service.scodex.svc.cluster.local

